name: My Second CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say HELLO
        run: echo "HELLO Hameedah! My second CI pipeline is working."

      - name: Check Linux
        run: uname -a

      - name: Run test
        run: bash test.sh

      - name: Create build file
        run: echo "This file was created by the build job." > build.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build-file
          path: build.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: my-build-file

      - name: Read build file
        run: cat build.txt

      - name: Test job
        run: echo "This is my second job!"
